De code die hieronder staan import numpy en time
Hij maakt daarna een matrix van 3x3 aan en vult de variables in die hij al in de matrix heeft staan

In [1]:
import numpy
import time

size = (3,3)

matrix = numpy.zeros(shape=size)

matrix[0][0] = 2
matrix[2][2] = 8 


Hieronder staan wat functies wat de algoritme gebruikt.
winner functie deze functie laat de matrix zien als hij klaar is
check_matrix functie deze functie controleerd of de matrix een magic square is zoja geeft hij true terug zo niet false
check functie deze functie controleerd of hij de punt in de matrix kan veranderen dit heeft hij nodig zodat hij niet de al ingevulde getallen overschrijft

In [2]:
def winner(matrix):
    print("==================")
    print(matrix)
    print("Success!!")

def check_matrix(matrix):
    for row in matrix:
        if sum(row) != 15:
            return False
    for i in range(0, 3):
        col = matrix[:, i]
        if sum(col) != 15:
            return False
    if matrix[0][0] + matrix[1][1] + matrix[2][2] != 15:
        return False
    if matrix[0][2] + matrix[1][1] + matrix[2][0] != 15:
        return False
    if len(numpy.unique(matrix)) != size[0] * size[1]:
        return False
    return True

def check(x, y):
    for item in dont_handle:
        if item == [y, x]:
            return True
    return False

De code hieronder maakt wat indexes aan om de algoritme wat makkelijker te maken. Zo vind hij de punten waar al een ingevuld getal staat en welke index de laatste index is in de matrix. Ook zet hij de matrixes in een lijst zodat we makkelijk kunnen zien welke volgorde we aanhouden om 1 bij toe te voegen

In [3]:

indexes = []
last_to_check = []
indexes_cord = {}
dont_handle = []

for i in range(0, size[0]):
    for j in range(0, size[1]):
        indexes.append([i, j])
        indexes_cord[f"{[i,j]}"] = len(indexes) - 1
        if matrix[i][j] != 0:
            dont_handle.append([i,j])
        
        else:
            last_to_check = [i, j]


Hieronder staat de algoritme die hij gebruikt om de magic square te berekenen. Deze algoritme probeert elke mogelijkheid tot hij de mogelijkheid tegen komt wat een juiste magic square is. Hij voert op de laatste index steeds 1 bij tot hij de 9 bereikt en dan voegt hij 1 bij de vorige index tot die 9 bereikt en dan voegt hij bij zijn vorige index 1 bij etc. Elke keer als hij alles heeft toegevoegd controleerd hij of het een magic square is zoja voert hij de winner functie uit en stopt hij de loop

In [4]:
busy = True
while busy:
    for y in range(0, size[0]):
        for x in range(0, size[1]):
            if check(x, y):
                continue
            index = indexes_cord[f"{[y,x]}"]
            if matrix[y][x] == 10:
                index = index - 1
                new_i = indexes[index]
                while check(new_i[1], new_i[0]):
                    index = index - 1
                    new_i = indexes[index]
                matrix[new_i[0]][new_i[1]] += 1
                matrix[y][x] = 1
            elif [y, x] == last_to_check:
                matrix[y][x] += 1
            if check_matrix(matrix):
                winner(matrix)
                busy = False

[[2. 7. 6.]
 [9. 5. 1.]
 [4. 3. 8.]]
Success!!
